### ISSUE TITLE
No more features in this reader, you should call hasNext() to check for feature availability

### ISSUE THREAD

**Issue by jonescc** [aodn/geoserver-build#273] opened 2018-05-09 04:48 UTC
NCWMS Abomination is throwing this error regularly trying to retrieve files creating noise in the logs.

Would be better if we just check hasNext.

```

01/04/201800:00:45.000 +1100 | 31 Mar 13:00:45 ERROR [geoserver.ows] -  java.util.NoSuchElementException: No more features in this reader, you should call hasNext() to check for feature availability 	at org.geotools.jdbc.JDBCFeatureReader.next(JDBCFeatureReader.java:298) 	at org.geotools.jdbc.JDBCFeatureReader.next(JDBCFeatureReader.java:75) 	at org.geotools.data.store.ContentFeatureCollection$WrappingFeatureIterator.next(ContentFeatureCollection.java:153) 	at org.geotools.data.store.ContentFeatureCollection$WrappingFeatureIterator.next(ContentFeatureCollection.java:133) 	at au.org.emii.geoserver.wms.GeoserverUrlIndex.getUrlForTimestamp(GeoserverUrlIndex.java:62) 	at au.org.emii.geoserver.wms.Ncwms.getWmsUrl(Ncwms.java:200) 	at au.org.emii.geoserver.wms.Ncwms.proxyWmsRequest(Ncwms.java:100) 	at au.org.emii.geoserver.wms.Ncwms.proxyWmsRequest(Ncwms.java:91) 	at au.org.emii.geoserver.wms.Ncwms.getMap(Ncwms.java:76) 	at sun.reflect.GeneratedMethodAccessor253.invoke(Unknown Source) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:606) 	at org.geoserver.ows.Dispatcher.execute(Dispatcher.java:845) 	at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:275) 	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153) 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48) 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923) 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852) 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882) 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:75) 	at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:71) 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71) 	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:46) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:50) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:311) 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69) 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116) 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83) 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73) 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323) 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69) 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73) 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323) 	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:54) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323) 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69) 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150) 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73) 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92) 	at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:83) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323) 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69) 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) 	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:53) 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73) 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323) 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173) 	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:135) 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:83) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:48) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:48) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:44) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110) 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506) 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683) 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962) 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445) 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115) 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637) 	at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2492) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622) 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ccmoloney** [comment] 2018-05-25 05:54
It's easy to add a check to see if the iterator.hasNext() is true - but I'm not sure that will stop errors being thrown.  This bit of code seems to be trying to determine the WMS URL for the layer.  If the iterator doesn't have anything in it - then we have not been able to determine the WMS URL.  The two places this is invoked from are the getMetaDataJson and the proxyWmsRequest methods of Ncwms.java.

The question is - what do we do if we can't get a WMS URL in these two places?  Neither calling method seems to handle a null WMS URL being returned at this stage.  It looks to me like we should add a check for iterator.hasNext - but in the case where there is no element in the iterator, then the best we can do is return null.  Then - it looks likely that we'll have to raise an error in those calling methods anyway.

**Comment by ccmoloney** [comment] 2018-05-28 04:15
I have added some debugging around this call to see if we can identify which layers are causing the error to be thrown - so that we can work out the root cause.

**Comment by ccmoloney** [comment] 2018-05-28 04:37
Looking at some of these in the logs - it looks to me like they are preceded by:

```
25 May 05:18:31 INFO [geoserver.filters] - 172.31.37.70 "GET /geoserver/ncwms?service=ncwms&request=GetMap&version=1.1.1&format=image/png&bbox=-180,-90,180,90&srs=EPSG:4326&width=1&height=1&STYLES=&LAYERS=acorn_hourly_avg_newc_qc_timeseries_url/sea_water_velocity" took 18ms
```

Are we unable to determine the WMS URL for acorn_hourly_avg_newc_qc_timeseries_url/sea_water_velocity?

**Comment by ccmoloney** [comment] 2018-05-28 04:42
Hmmm - definitely reproducable by running (GET) this:

```
http://geoserver-123.aodn.org.au/geoserver/ncwms?service=ncwms&request=GetMap&version=1.1.1&format=image/png&bbox=-180,-90,180,90&srs=EPSG:4326&width=1&height=1&STYLES=&LAYERS=acorn_hourly_avg_newc_qc_timeseries_url/sea_water_velocity
```

**Comment by ccmoloney** [comment] 2018-05-28 04:51
Looking at the frequency of these events - they are happening every 15 minutes - virtually exactly...
I'm thinking that they are being caused by one of the checks that we do regularly?  Maybe the online resource monitor?

**Comment by ccmoloney** [comment] 2018-05-28 23:14
If i try the same request against another layer it seems to return something (does not throw an error):

http://geoserver-123.aodn.org.au/geoserver/ncwms?service=ncwms&request=GetMap&version=1.1.1&format=image/png&bbox=-180,-90,180,90&srs=EPSG:4326&width=1&height=1&STYLES=&LAYERS=srs_ghrsst_l3s_1d_dn_url/sea_surface_temperature

**Comment by ccmoloney** [comment] 2018-05-28 23:56
It turns out that the GetFeature call to list files for that collection is returning 0 rows - ie: there is no content for that collection.  We will have to have a look at why that is happening.  It may be that there is an issue with the pipeline for that collection?

The code has been updated to add extra logging when these types of issues occur to hopefully allow us to identify future problems in a timely manner.

**Comment by ccmoloney** [comment] 2018-05-28 23:57
@pblain Do we assign this one to POs to investigate?

**Comment by pblain** [comment] 2018-05-29 03:50
@ccmoloney - You could log a content issue to look into why this collection returns zero rows. It probably doesn't make sense for you to start getting into pipeline territory. Just make sure you explain the problem in the issue so that POs can understand what's going on.

**Comment by ggalibert** [comment] 2018-05-29 04:00
There is no row returned because we haven't received any data yet for this collection. We should receive some in the near future though. A matter of weeks if not months.

**Comment by ccmoloney** [comment] 2018-05-29 04:31
Cool - thanks @ggalibert

**Comment by ccmoloney** [comment] 2018-05-29 06:08
This layer is in the production portal currently - but is in bad health (as you would expect).  Would we generally wait until we have data before publishing a layer to production?

**Comment by jonescc** [comment] 2018-05-30 06:35
The online resource monitor continually checks this layer in prod and gets errors doing so - this is creating noise in the logs and makes it more difficult for us to find issues that need to be fixed.   Can we not publish metadata for layers which don't have data for them yet?  May be confusing for others as well.

**Comment by ggalibert** [comment] 2018-05-30 06:46
We've just removed the metadata record from prod. Should be out tomorrow.

**Comment by lwgordonimos** [comment] 2018-06-04 23:49
Closing issue @pblain as logging added

**Closed by lwgordonimos** 2018-06-04 23:49 UTC
Labels: bug
